### ISSUE TITLE
Have error in exercise 02

### ISSUE THREAD

**Issue by jungwoo9** [jungwoo9/zero-to-mastery-learn-pytorch-for-deep-learning#1]
Cannot solve the error below.

"RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions."

which is in the last part of training loop in section 7.

**Comment by jungwoo9** [comment]
commit is 24f5e81

**Comment by jungwoo9** [comment]
Fixed. The problem was that out_features was incorrect when the model is instantiated. It should be 3 but it was 1.

commit: d12ad9b

**Comment by jungwoo9** [comment]
Fixed. The problem was that out_features was incorrect when the model is instantiated. It should be 3 but it was 1.

commit: https://github.com/jungwoo9/zero-to-mastery-learn-pytorch-for-deep-learning/commit/d12ad9b617cc8dc7c13e761aa65b36ba636938b8
